/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: 'var(--primary-50, #F0FDFA)',
          100: 'var(--primary-100, #CCFBF1)',
          200: 'var(--primary-200, #99F6E4)',
          300: 'var(--primary-300, #5EEAD4)',
          400: 'var(--primary-400, #2DD4BF)',
          500: 'var(--primary-500, #0F766E)',
          600: 'var(--primary-600, #0D9488)',
          700: 'var(--primary-700, #0F766E)',
          800: 'var(--primary-800, #115E59)',
          900: 'var(--primary-900, #134E4A)',
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        /* Hallaqi Brand Palette */
        'hallaqi': {
          50: '#F0FDFA',
          100: '#CCFBF1',
          200: '#99F6E4',
          300: '#5EEAD4',
          400: '#2DD4BF',
          500: '#0F766E',
          600: '#0D9488',
          700: '#0F766E',
          800: '#115E59',
          900: '#134E4A',
        },
        'hallaqi-dark': {
          50: '#0C4A6E',
          100: '#164E63',
          200: '#155E75',
          300: '#0E7490',
          400: '#0891B2',
          500: '#06B6D4',
          600: '#22D3EE',
          700: '#67E8F9',
          800: '#A5F3FC',
          900: '#CFFAFE',
        },
        'hallaqi-accent': {
          DEFAULT: '#F59E0B',
          50: '#FFFBEB',
          100: '#FEF3C7',
          200: '#FDE68A',
          300: '#FCD34D',
          400: '#FBBF24',
          500: '#F59E0B',
          600: '#D97706',
          700: '#B45309',
          800: '#92400E',
          900: '#78350F',
        },
        /* Dynamic Theme Tokens */
        'bg-base': 'var(--bg-base, #F0FDFA)',
        'bg-card': 'var(--bg-card, #FFFFFF)',
        'bg-elevated': 'var(--bg-elevated, #CCFBF1)',
        'text-primary': 'var(--text-primary, #0F172A)',
        'text-secondary': 'var(--text-secondary, #334155)',
        'text-tertiary': 'var(--text-tertiary, #64748B)',
        'border-subtle': 'var(--border-subtle, #99F6E4)',
        'border-focus': 'var(--border-focus, #0F766E)',
        'success': 'var(--success, #059669)',
        'warning': 'var(--warning, #D97706)',
        'error': 'var(--error, #DC2626)',
        'gold': 'var(--gold, #F59E0B)',
      },
      fontFamily: {
        arabic: ['"Noto Sans Arabic"', 'sans-serif'],
        display: ['"Playfair Display"', 'serif'],
        body: ['"Noto Sans Arabic"', '"Inter"', 'sans-serif'],
        inter: ['"Inter"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        '2xl': '16px',
        '3xl': '24px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'card': '0 2px 12px rgba(15, 118, 110, 0.08)',
        'float': '0 8px 32px rgba(15, 118, 110, 0.14)',
        'button': '0 4px 14px rgba(15, 118, 110, 0.35)',
        'dark-card': '0 2px 12px rgba(0, 0, 0, 0.3)',
        'accent': '0 4px 14px rgba(245, 158, 11, 0.35)',
      },
      transitionTimingFunction: {
        'ease-default': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'ease-spring': 'cubic-bezier(0.32, 0.72, 0, 1)',
        'ease-out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'ease-in-out-custom': 'cubic-bezier(0.65, 0, 0.35, 1)',
      },
      transitionDuration: {
        'fast': '150ms',
        'base': '300ms',
        'slow': '500ms',
        'dramatic': '800ms',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-indicator": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.2)" },
        },
        "skeleton-shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "bounce-badge": {
          "0%, 100%": { transform: "scale(1)" },
          "25%": { transform: "scale(1.2)" },
          "50%": { transform: "scale(1)" },
          "75%": { transform: "scale(1.1)" },
        },
        "slide-up": {
          "0%": { transform: "translateY(24px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "logo-pulse": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.7", transform: "scale(1.05)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-indicator": "pulse-indicator 2s ease-in-out infinite",
        "skeleton": "skeleton-shimmer 1.5s ease-in-out infinite",
        "bounce-badge": "bounce-badge 0.6s ease-out",
        "slide-up": "slide-up 0.5s ease-out forwards",
        "fade-in": "fade-in 0.3s ease-out forwards",
        "logo-pulse": "logo-pulse 2s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
      },
      maxWidth: {
        'mobile': '480px',
      },
      height: {
        'navbar': '56px',
        'bottom-nav': '72px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
